server {
    listen 80;
    
    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        # Try to serve file directly, fallback to index.html for React Router SPA
        try_files $uri $uri/ /index.html;
    }
}
